# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rackup` gem.
# Please instead update this file by running `bin/tapioca gem rackup`.

# source://rackup//lib/rack/handler.rb#5
module Rack
  class << self
    # source://rack/3.0.0/lib/rack/version.rb#31
    def release; end

    # source://rack/3.0.0/lib/rack/version.rb#23
    def version; end
  end
end

# source://rack/3.0.0/lib/rack/constants.rb#19
Rack::CACHE_CONTROL = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#20
Rack::CONTENT_LENGTH = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#21
Rack::CONTENT_TYPE = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#32
Rack::DELETE = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#22
Rack::ETAG = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#23
Rack::EXPIRES = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/file.rb#8
Rack::File = Rack::Files

# source://rack/3.0.0/lib/rack/constants.rb#28
Rack::GET = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#33
Rack::HEAD = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#7
Rack::HTTPS = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#16
Rack::HTTP_COOKIE = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#5
Rack::HTTP_HOST = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#6
Rack::HTTP_PORT = T.let(T.unsafe(nil), String)

# source://rackup//lib/rack/handler.rb#6
Rack::Handler = Rackup::Handler

# source://rack/3.0.0/lib/rack/constants.rb#35
Rack::LINK = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#34
Rack::OPTIONS = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#31
Rack::PATCH = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#8
Rack::PATH_INFO = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#29
Rack::POST = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#30
Rack::PUT = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#12
Rack::QUERY_STRING = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#42
Rack::RACK_ERRORS = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#49
Rack::RACK_HIJACK = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#44
Rack::RACK_INPUT = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#50
Rack::RACK_IS_HIJACK = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#43
Rack::RACK_LOGGER = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#62
Rack::RACK_METHODOVERRIDE_ORIGINAL_METHOD = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#52
Rack::RACK_MULTIPART_BUFFER_SIZE = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#53
Rack::RACK_MULTIPART_TEMPFILE_FACTORY = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#51
Rack::RACK_RECURSIVE_INCLUDE = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#58
Rack::RACK_REQUEST_COOKIE_HASH = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#59
Rack::RACK_REQUEST_COOKIE_STRING = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#56
Rack::RACK_REQUEST_FORM_HASH = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#55
Rack::RACK_REQUEST_FORM_INPUT = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#57
Rack::RACK_REQUEST_FORM_VARS = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#60
Rack::RACK_REQUEST_QUERY_HASH = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#61
Rack::RACK_REQUEST_QUERY_STRING = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#54
Rack::RACK_RESPONSE_FINISHED = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#45
Rack::RACK_SESSION = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#46
Rack::RACK_SESSION_OPTIONS = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#47
Rack::RACK_SHOWSTATUS_DETAIL = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#41
Rack::RACK_TEMPFILES = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#48
Rack::RACK_URL_SCHEME = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#40
Rack::RACK_VERSION = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/version.rb#28
Rack::RELEASE = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#9
Rack::REQUEST_METHOD = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#10
Rack::REQUEST_PATH = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#11
Rack::SCRIPT_NAME = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#14
Rack::SERVER_NAME = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#15
Rack::SERVER_PORT = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#13
Rack::SERVER_PROTOCOL = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#24
Rack::SET_COOKIE = T.let(T.unsafe(nil), String)

# source://rackup//lib/rack/server.rb#6
Rack::Server = Rackup::Server

# source://rack/3.0.0/lib/rack/constants.rb#37
Rack::TRACE = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#25
Rack::TRANSFER_ENCODING = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/constants.rb#36
Rack::UNLINK = T.let(T.unsafe(nil), String)

# source://rack/3.0.0/lib/rack/version.rb#16
Rack::VERSION = T.let(T.unsafe(nil), Array)

# source://rack/3.0.0/lib/rack/version.rb#19
Rack::VERSION_STRING = T.let(T.unsafe(nil), String)

# source://rackup//lib/rackup/handler.rb#3
module Rackup; end

# *Handlers* connect web servers with Rack.
#
# Rackup includes Handlers for WEBrick and CGI.
#
# Handlers usually are activated by calling <tt>MyHandler.run(myapp)</tt>.
# A second optional hash can be passed to include server-specific
# configuration.
#
# source://rackup//lib/rackup/handler.rb#11
module Rackup::Handler
  class << self
    # source://rackup//lib/rackup/handler.rb#27
    def [](name); end

    # source://rackup//lib/rackup/handler.rb#81
    def default; end

    # source://rackup//lib/rackup/handler.rb#37
    def get(name); end

    # Select first available Rack handler given an `Array` of server names.
    # Raises `LoadError` if no handler was found.
    #
    #   > pick ['puma', 'webrick']
    #   => Rackup::Handler::WEBrick
    #
    # @raise [LoadError]
    #
    # source://rackup//lib/rackup/handler.rb#66
    def pick(server_names); end

    # Register a named handler class.
    #
    # source://rackup//lib/rackup/handler.rb#15
    def register(name, klass); end

    # Transforms server-name constants to their canonical form as filenames,
    # then tries to require them but silences the LoadError if not found
    #
    # Naming convention:
    #
    #   Foo # => 'foo'
    #   FooBar # => 'foo_bar.rb'
    #   FooBAR # => 'foobar.rb'
    #   FOObar # => 'foobar.rb'
    #   FOOBAR # => 'foobar.rb'
    #   FooBarBaz # => 'foo_bar_baz.rb'
    #
    # source://rackup//lib/rackup/handler.rb#103
    def require_handler(prefix, const_name); end
  end
end

# source://rackup//lib/rackup/handler/cgi.rb#5
class Rackup::Handler::CGI
  include ::Rack

  class << self
    # source://rackup//lib/rackup/handler/cgi.rb#8
    def run(app, **options); end

    # source://rackup//lib/rackup/handler/cgi.rb#48
    def send_body(body); end

    # source://rackup//lib/rackup/handler/cgi.rb#37
    def send_headers(status, headers); end

    # source://rackup//lib/rackup/handler/cgi.rb#13
    def serve(app); end
  end
end

# source://rackup//lib/rackup/handler.rb#56
Rackup::Handler::RACKUP_HANDLER = T.let(T.unsafe(nil), String)

# source://rackup//lib/rackup/handler.rb#55
Rackup::Handler::RACK_HANDLER = T.let(T.unsafe(nil), String)

# source://rackup//lib/rackup/handler.rb#58
Rackup::Handler::SERVER_NAMES = T.let(T.unsafe(nil), Array)

# source://rackup//lib/rackup/handler/webrick.rb#29
class Rackup::Handler::WEBrick < ::WEBrick::HTTPServlet::AbstractServlet
  include ::Rack

  # @return [WEBrick] a new instance of WEBrick
  #
  # source://rackup//lib/rackup/handler/webrick.rb#67
  def initialize(server, app); end

  # source://rackup//lib/rackup/handler/webrick.rb#72
  def service(req, res); end

  class << self
    # @yield [@server]
    #
    # source://rackup//lib/rackup/handler/webrick.rb#32
    def run(app, **options); end

    # source://rackup//lib/rackup/handler/webrick.rb#60
    def shutdown; end

    # source://rackup//lib/rackup/handler/webrick.rb#50
    def valid_options; end
  end
end

# source://rackup//lib/rackup/server.rb#19
class Rackup::Server
  # Options may include:
  # * :app
  #     a rack application to run (overrides :config and :builder)
  # * :builder
  #     a string to evaluate a Rack::Builder from
  # * :config
  #     a rackup configuration file path to load (.ru)
  # * :environment
  #     this selects the middleware that will be wrapped around
  #     your application. Default options available are:
  #       - development: CommonLogger, ShowExceptions, and Lint
  #       - deployment: CommonLogger
  #       - none: no extra middleware
  #     note: when the server is a cgi server, CommonLogger is not included.
  # * :server
  #     choose a specific Rackup::Handler, e.g. cgi, fcgi, webrick
  # * :daemonize
  #     if truthy, the server will daemonize itself (fork, detach, etc)
  #     if :noclose, the server will not close STDOUT/STDERR
  # * :pid
  #     path to write a pid file after daemonize
  # * :Host
  #     the host address to bind to (used by supporting Rackup::Handler)
  # * :Port
  #     the port to bind to (used by supporting Rackup::Handler)
  # * :AccessLog
  #     webrick access log options (or supporting Rackup::Handler)
  # * :debug
  #     turn on debug output ($DEBUG = true)
  # * :warn
  #     turn on warnings ($-w = true)
  # * :include
  #     add given paths to $LOAD_PATH
  # * :require
  #     require the given libraries
  #
  # Additional options for profiling app initialization include:
  # * :heapfile
  #     location for ObjectSpace.dump_all to write the output to
  # * :profile_file
  #     location for CPU/Memory (StackProf) profile output (defaults to a tempfile)
  # * :profile_mode
  #     StackProf profile mode (cpu|wall|object)
  #
  # @return [Server] a new instance of Server
  #
  # source://rackup//lib/rackup/server.rb#227
  def initialize(options = T.unsafe(nil)); end

  # source://rackup//lib/rackup/server.rb#259
  def app; end

  # source://rackup//lib/rackup/server.rb#245
  def default_options; end

  # source://rackup//lib/rackup/server.rb#293
  def middleware; end

  # source://rackup//lib/rackup/server.rb#240
  def options; end

  # Sets the attribute options
  #
  # @param value the value to set the attribute options to.
  #
  # source://rackup//lib/rackup/server.rb#182
  def options=(_arg0); end

  # source://rackup//lib/rackup/server.rb#341
  def server; end

  # source://rackup//lib/rackup/server.rb#297
  def start(&block); end

  private

  # source://rackup//lib/rackup/server.rb#410
  def build_app(app); end

  # source://rackup//lib/rackup/server.rb#346
  def build_app_and_options_from_config; end

  # source://rackup//lib/rackup/server.rb#392
  def build_app_from_string; end

  # source://rackup//lib/rackup/server.rb#439
  def check_pid!; end

  # source://rackup//lib/rackup/server.rb#424
  def daemonize_app; end

  # source://rackup//lib/rackup/server.rb#453
  def exit_with_pid(pid); end

  # source://rackup//lib/rackup/server.rb#354
  def handle_profiling(heapfile, profile_mode, filename); end

  # source://rackup//lib/rackup/server.rb#382
  def make_profile_name(filename); end

  # source://rackup//lib/rackup/server.rb#406
  def opt_parser; end

  # source://rackup//lib/rackup/server.rb#396
  def parse_options(args); end

  # source://rackup//lib/rackup/server.rb#420
  def wrapped_app; end

  # source://rackup//lib/rackup/server.rb#431
  def write_pid; end

  class << self
    # source://rackup//lib/rackup/server.rb#270
    def default_middleware_by_environment; end

    # source://rackup//lib/rackup/server.rb#264
    def logging_middleware; end

    # source://rackup//lib/rackup/server.rb#288
    def middleware; end

    # Start a new rack server (like running rackup). This will parse ARGV and
    # provide standard ARGV rackup options, defaulting to load 'config.ru'.
    #
    # Providing an options hash will prevent ARGV parsing and will not include
    # any default options.
    #
    # This method can be used to very easily launch a CGI application, for
    # example:
    #
    #  Rack::Server.start(
    #    :app => lambda do |e|
    #      [200, {'content-type' => 'text/html'}, ['hello world']]
    #    end,
    #    :server => 'cgi'
    #  )
    #
    # Further options available here are documented on Rack::Server#initialize
    #
    # source://rackup//lib/rackup/server.rb#178
    def start(options = T.unsafe(nil)); end
  end
end

# source://rackup//lib/rackup/server.rb#20
class Rackup::Server::Options
  # source://rackup//lib/rackup/server.rb#140
  def handler_opts(options); end

  # source://rackup//lib/rackup/server.rb#21
  def parse!(args); end
end

# source://rackup//lib/rackup/version.rb#24
Rackup::VERSION = T.let(T.unsafe(nil), String)

# This monkey patch allows for applications to perform their own chunking
# through WEBrick::HTTPResponse if rack is set to true.
#
# source://rackup//lib/rackup/handler/webrick.rb#12
class WEBrick::HTTPResponse
  # Returns the value of attribute rack.
  #
  # source://rackup//lib/rackup/handler/webrick.rb#13
  def rack; end

  # Sets the attribute rack
  #
  # @param value the value to set the attribute rack to.
  #
  # source://rackup//lib/rackup/handler/webrick.rb#13
  def rack=(_arg0); end

  # source://rackup//lib/rackup/handler/webrick.rb#16
  def setup_header; end
end
