# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `websocket-client-simple` gem.
# Please instead update this file by running `bin/tapioca gem websocket-client-simple`.

module WebSocket::Client; end

module WebSocket::Client::Simple
  class << self
    # @yield [client]
    #
    # source://websocket-client-simple//lib/websocket-client-simple/client.rb#5
    def connect(url, options = T.unsafe(nil)); end
  end
end

class WebSocket::Client::Simple::Client
  include ::EventEmitter
  include ::EventEmitter::InstanceMethods

  # source://websocket-client-simple//lib/websocket-client-simple/client.rb#87
  def close; end

  # @return [Boolean]
  #
  # source://websocket-client-simple//lib/websocket-client-simple/client.rb#103
  def closed?; end

  # source://websocket-client-simple//lib/websocket-client-simple/client.rb#16
  def connect(url, options = T.unsafe(nil)); end

  # Returns the value of attribute handshake.
  #
  # source://websocket-client-simple//lib/websocket-client-simple/client.rb#14
  def handshake; end

  # @return [Boolean]
  #
  # source://websocket-client-simple//lib/websocket-client-simple/client.rb#99
  def open?; end

  # source://websocket-client-simple//lib/websocket-client-simple/client.rb#72
  def send(data, opt = T.unsafe(nil)); end

  # source://discordrb/3.4.0/lib/discordrb/websocket.rb#11
  def thread; end

  # Returns the value of attribute url.
  #
  # source://websocket-client-simple//lib/websocket-client-simple/client.rb#14
  def url; end
end

# source://websocket-client-simple//lib/websocket-client-simple/version.rb#4
WebSocket::Client::Simple::VERSION = T.let(T.unsafe(nil), String)
