app = "babkabot"
primary_region = "den"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8080
force_https = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
